### ISSUE TITLE
Throws error with Contao 4.9.27

### ISSUE THREAD

**Issue by Aybee** [cliffparnitzky/TechnicalValueRegex#1]
Hello Cliff,

this file https://github.com/cliffparnitzky/TechnicalValueRegex/blob/master/system/modules/technicalValueRegex/dca/tl_dma_eg_fields.php
throws an error. 
`No columns specified for table tl_dma_eg_fields`

See also here https://github.com/contao/contao/issues/4253

Does this extension needs that file at all? I think that noone uses dma_element_generator anymore.
https://github.com/DMAGmbH/dma_elementgenerator

Your extension BackendCustomCss https://github.com/cliffparnitzky/BackendCustomCss requires TechnicalValueRegex.

**Comment by cliffparnitzky** [comment]
This is not longer needed. If https://github.com/cliffparnitzky/BackendCustomCss/issues/5 completed, this extension can be archived.

**Comment by Aybee** [comment]
Thank you.
